// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: service.proto

package grpc_services

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreateUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateUpdateRequest) Reset() {
	*x = UserCreateUpdateRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateUpdateRequest) ProtoMessage() {}

func (x *UserCreateUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserCreateUpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreateUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserCreateUpdateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreateUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserReadDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReadDeleteRequest) Reset() {
	*x = UserReadDeleteRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReadDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReadDeleteRequest) ProtoMessage() {}

func (x *UserReadDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReadDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserReadDeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserReadDeleteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type ChatCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdChat        int64                  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCreateRequest) Reset() {
	*x = ChatCreateRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCreateRequest) ProtoMessage() {}

func (x *ChatCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCreateRequest.ProtoReflect.Descriptor instead.
func (*ChatCreateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ChatCreateRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *ChatCreateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ChatCreateRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ChatUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdChat        int64                  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUpdateRequest) Reset() {
	*x = ChatUpdateRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdateRequest) ProtoMessage() {}

func (x *ChatUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdateRequest.ProtoReflect.Descriptor instead.
func (*ChatUpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ChatUpdateRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *ChatUpdateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type ChatDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdChat        int64                  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDeleteRequest) Reset() {
	*x = ChatDeleteRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDeleteRequest) ProtoMessage() {}

func (x *ChatDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDeleteRequest.ProtoReflect.Descriptor instead.
func (*ChatDeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ChatDeleteRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type ChatReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdChat        int64                  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReadRequest) Reset() {
	*x = ChatReadRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReadRequest) ProtoMessage() {}

func (x *ChatReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReadRequest.ProtoReflect.Descriptor instead.
func (*ChatReadRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ChatReadRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *ChatReadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdChat        int64                  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	StartDate     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *Chat) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *Chat) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Chat) GetStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Chat) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Chats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chats) Reset() {
	*x = Chats{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chats) ProtoMessage() {}

func (x *Chats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chats.ProtoReflect.Descriptor instead.
func (*Chats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *Chats) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type MessageCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IdChat        int64                  `protobuf:"varint,2,opt,name=idChat,proto3" json:"idChat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreateRequest) Reset() {
	*x = MessageCreateRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreateRequest) ProtoMessage() {}

func (x *MessageCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreateRequest.ProtoReflect.Descriptor instead.
func (*MessageCreateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *MessageCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageCreateRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type MessageReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMessage     int64                  `protobuf:"varint,1,opt,name=idMessage,proto3" json:"idMessage,omitempty"`
	IdChat        int64                  `protobuf:"varint,2,opt,name=idChat,proto3" json:"idChat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReadRequest) Reset() {
	*x = MessageReadRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadRequest) ProtoMessage() {}

func (x *MessageReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadRequest.ProtoReflect.Descriptor instead.
func (*MessageReadRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *MessageReadRequest) GetIdMessage() int64 {
	if x != nil {
		return x.IdMessage
	}
	return 0
}

func (x *MessageReadRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type MessageUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMessage     int64                  `protobuf:"varint,1,opt,name=idMessage,proto3" json:"idMessage,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdateRequest) Reset() {
	*x = MessageUpdateRequest{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdateRequest) ProtoMessage() {}

func (x *MessageUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdateRequest.ProtoReflect.Descriptor instead.
func (*MessageUpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *MessageUpdateRequest) GetIdMessage() int64 {
	if x != nil {
		return x.IdMessage
	}
	return 0
}

func (x *MessageUpdateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MessageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMessage     int64                  `protobuf:"varint,1,opt,name=idMessage,proto3" json:"idMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleteRequest) Reset() {
	*x = MessageDeleteRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleteRequest) ProtoMessage() {}

func (x *MessageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleteRequest.ProtoReflect.Descriptor instead.
func (*MessageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *MessageDeleteRequest) GetIdMessage() int64 {
	if x != nil {
		return x.IdMessage
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMessage     int64                  `protobuf:"varint,1,opt,name=idMessage,proto3" json:"idMessage,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IdChat        int64                  `protobuf:"varint,4,opt,name=idChat,proto3" json:"idChat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *Message) GetIdMessage() int64 {
	if x != nil {
		return x.IdMessage
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type Messages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messages) Reset() {
	*x = Messages{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messages) ProtoMessage() {}

func (x *Messages) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messages.ProtoReflect.Descriptor instead.
func (*Messages) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *Messages) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x17UserCreateUpdateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"-\n" +
	"\x15UserReadDeleteRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"L\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"$\n" +
	"\x05Users\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\"[\n" +
	"\x11ChatCreateRequest\x12\x16\n" +
	"\x06idChat\x18\x01 \x01(\x03R\x06idChat\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"E\n" +
	"\x11ChatUpdateRequest\x12\x16\n" +
	"\x06idChat\x18\x01 \x01(\x03R\x06idChat\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"+\n" +
	"\x11ChatDeleteRequest\x12\x16\n" +
	"\x06idChat\x18\x01 \x01(\x03R\x06idChat\"?\n" +
	"\x0fChatReadRequest\x12\x16\n" +
	"\x06idChat\x18\x01 \x01(\x03R\x06idChat\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\x88\x01\n" +
	"\x04Chat\x12\x16\n" +
	"\x06idChat\x18\x01 \x01(\x03R\x06idChat\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x128\n" +
	"\tstartDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"$\n" +
	"\x05Chats\x12\x1b\n" +
	"\x05chats\x18\x01 \x03(\v2\x05.ChatR\x05chats\"H\n" +
	"\x14MessageCreateRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06idChat\x18\x02 \x01(\x03R\x06idChat\"J\n" +
	"\x12MessageReadRequest\x12\x1c\n" +
	"\tidMessage\x18\x01 \x01(\x03R\tidMessage\x12\x16\n" +
	"\x06idChat\x18\x02 \x01(\x03R\x06idChat\"N\n" +
	"\x14MessageUpdateRequest\x12\x1c\n" +
	"\tidMessage\x18\x01 \x01(\x03R\tidMessage\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"4\n" +
	"\x14MessageDeleteRequest\x12\x1c\n" +
	"\tidMessage\x18\x01 \x01(\x03R\tidMessage\"\x93\x01\n" +
	"\aMessage\x12\x1c\n" +
	"\tidMessage\x18\x01 \x01(\x03R\tidMessage\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06idChat\x18\x04 \x01(\x03R\x06idChat\"0\n" +
	"\bMessages\x12$\n" +
	"\bmessages\x18\x01 \x03(\v2\b.MessageR\bmessages2\xfb\x05\n" +
	"\vDataService\x12/\n" +
	"\n" +
	"CreateUser\x12\x18.UserCreateUpdateRequest\x1a\x05.User\"\x00\x12*\n" +
	"\aGetUser\x12\x16.UserReadDeleteRequest\x1a\x05.User\"\x00\x12/\n" +
	"\n" +
	"UpdateUser\x12\x18.UserCreateUpdateRequest\x1a\x05.User\"\x00\x12>\n" +
	"\n" +
	"DeleteUser\x12\x16.UserReadDeleteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x06.Users\"\x00\x12)\n" +
	"\n" +
	"CreateChat\x12\x12.ChatCreateRequest\x1a\x05.Chat\"\x00\x12$\n" +
	"\aGetChat\x12\x10.ChatReadRequest\x1a\x05.Chat\"\x00\x12)\n" +
	"\n" +
	"UpdateChat\x12\x12.ChatUpdateRequest\x1a\x05.Chat\"\x00\x12:\n" +
	"\n" +
	"DeleteChat\x12\x12.ChatDeleteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\tListChats\x12\x16.UserReadDeleteRequest\x1a\x06.Chats\"\x00\x122\n" +
	"\rCreateMessage\x12\x15.MessageCreateRequest\x1a\b.Message\"\x00\x12-\n" +
	"\n" +
	"GetMessage\x12\x13.MessageReadRequest\x1a\b.Message\"\x00\x122\n" +
	"\rUpdateMessage\x12\x15.MessageUpdateRequest\x1a\b.Message\"\x00\x12@\n" +
	"\rDeleteMessage\x12\x15.MessageDeleteRequest\x1a\x16.google.protobuf.Empty\"\x00\x12/\n" +
	"\fListMessages\x12\x12.ChatDeleteRequest\x1a\t.Messages\"\x00B\x11Z\x0f.;grpc_servicesb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_service_proto_goTypes = []any{
	(*UserCreateUpdateRequest)(nil), // 0: UserCreateUpdateRequest
	(*UserReadDeleteRequest)(nil),   // 1: UserReadDeleteRequest
	(*User)(nil),                    // 2: User
	(*Users)(nil),                   // 3: Users
	(*ChatCreateRequest)(nil),       // 4: ChatCreateRequest
	(*ChatUpdateRequest)(nil),       // 5: ChatUpdateRequest
	(*ChatDeleteRequest)(nil),       // 6: ChatDeleteRequest
	(*ChatReadRequest)(nil),         // 7: ChatReadRequest
	(*Chat)(nil),                    // 8: Chat
	(*Chats)(nil),                   // 9: Chats
	(*MessageCreateRequest)(nil),    // 10: MessageCreateRequest
	(*MessageReadRequest)(nil),      // 11: MessageReadRequest
	(*MessageUpdateRequest)(nil),    // 12: MessageUpdateRequest
	(*MessageDeleteRequest)(nil),    // 13: MessageDeleteRequest
	(*Message)(nil),                 // 14: Message
	(*Messages)(nil),                // 15: Messages
	(*timestamp.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*empty.Empty)(nil),             // 17: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	2,  // 0: Users.users:type_name -> User
	16, // 1: Chat.startDate:type_name -> google.protobuf.Timestamp
	8,  // 2: Chats.chats:type_name -> Chat
	16, // 3: Message.timestamp:type_name -> google.protobuf.Timestamp
	14, // 4: Messages.messages:type_name -> Message
	0,  // 5: DataService.CreateUser:input_type -> UserCreateUpdateRequest
	1,  // 6: DataService.GetUser:input_type -> UserReadDeleteRequest
	0,  // 7: DataService.UpdateUser:input_type -> UserCreateUpdateRequest
	1,  // 8: DataService.DeleteUser:input_type -> UserReadDeleteRequest
	17, // 9: DataService.ListUsers:input_type -> google.protobuf.Empty
	4,  // 10: DataService.CreateChat:input_type -> ChatCreateRequest
	7,  // 11: DataService.GetChat:input_type -> ChatReadRequest
	5,  // 12: DataService.UpdateChat:input_type -> ChatUpdateRequest
	6,  // 13: DataService.DeleteChat:input_type -> ChatDeleteRequest
	1,  // 14: DataService.ListChats:input_type -> UserReadDeleteRequest
	10, // 15: DataService.CreateMessage:input_type -> MessageCreateRequest
	11, // 16: DataService.GetMessage:input_type -> MessageReadRequest
	12, // 17: DataService.UpdateMessage:input_type -> MessageUpdateRequest
	13, // 18: DataService.DeleteMessage:input_type -> MessageDeleteRequest
	6,  // 19: DataService.ListMessages:input_type -> ChatDeleteRequest
	2,  // 20: DataService.CreateUser:output_type -> User
	2,  // 21: DataService.GetUser:output_type -> User
	2,  // 22: DataService.UpdateUser:output_type -> User
	17, // 23: DataService.DeleteUser:output_type -> google.protobuf.Empty
	3,  // 24: DataService.ListUsers:output_type -> Users
	8,  // 25: DataService.CreateChat:output_type -> Chat
	8,  // 26: DataService.GetChat:output_type -> Chat
	8,  // 27: DataService.UpdateChat:output_type -> Chat
	17, // 28: DataService.DeleteChat:output_type -> google.protobuf.Empty
	9,  // 29: DataService.ListChats:output_type -> Chats
	14, // 30: DataService.CreateMessage:output_type -> Message
	14, // 31: DataService.GetMessage:output_type -> Message
	14, // 32: DataService.UpdateMessage:output_type -> Message
	17, // 33: DataService.DeleteMessage:output_type -> google.protobuf.Empty
	15, // 34: DataService.ListMessages:output_type -> Messages
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
