# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUsuario = channel.unary_unary(
                '/DataService/CreateUsuario',
                request_serializer=service__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=service__pb2.Usuario.FromString,
                _registered_method=True)
        self.GetUsuario = channel.unary_unary(
                '/DataService/GetUsuario',
                request_serializer=service__pb2.Email.SerializeToString,
                response_deserializer=service__pb2.Usuario.FromString,
                _registered_method=True)
        self.UpdateUsuario = channel.unary_unary(
                '/DataService/UpdateUsuario',
                request_serializer=service__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=service__pb2.Usuario.FromString,
                _registered_method=True)
        self.DeleteUsuario = channel.unary_unary(
                '/DataService/DeleteUsuario',
                request_serializer=service__pb2.Email.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUsuarios = channel.unary_unary(
                '/DataService/GetUsuarios',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.Usuarios.FromString,
                _registered_method=True)
        self.CreateChat = channel.unary_unary(
                '/DataService/CreateChat',
                request_serializer=service__pb2.ChatRequest.SerializeToString,
                response_deserializer=service__pb2.Chat.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/DataService/GetChat',
                request_serializer=service__pb2.DataChat.SerializeToString,
                response_deserializer=service__pb2.Chat.FromString,
                _registered_method=True)
        self.UpdateChat = channel.unary_unary(
                '/DataService/UpdateChat',
                request_serializer=service__pb2.ChatRequest.SerializeToString,
                response_deserializer=service__pb2.Chat.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/DataService/DeleteChat',
                request_serializer=service__pb2.idChat.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetChats = channel.unary_unary(
                '/DataService/GetChats',
                request_serializer=service__pb2.Email.SerializeToString,
                response_deserializer=service__pb2.Chats.FromString,
                _registered_method=True)
        self.CreateMensagem = channel.unary_unary(
                '/DataService/CreateMensagem',
                request_serializer=service__pb2.MensagemRequest.SerializeToString,
                response_deserializer=service__pb2.Mensagem.FromString,
                _registered_method=True)
        self.GetMensagem = channel.unary_unary(
                '/DataService/GetMensagem',
                request_serializer=service__pb2.DataMensagem.SerializeToString,
                response_deserializer=service__pb2.Mensagem.FromString,
                _registered_method=True)
        self.UpdateMensagem = channel.unary_unary(
                '/DataService/UpdateMensagem',
                request_serializer=service__pb2.MensagemRequest.SerializeToString,
                response_deserializer=service__pb2.Mensagem.FromString,
                _registered_method=True)
        self.DeleteMensagem = channel.unary_unary(
                '/DataService/DeleteMensagem',
                request_serializer=service__pb2.idMensagem.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMensagens = channel.unary_unary(
                '/DataService/GetMensagens',
                request_serializer=service__pb2.idChat.SerializeToString,
                response_deserializer=service__pb2.Mensagens.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUsuario(self, request, context):
        """Usuario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChat(self, request, context):
        """Chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMensagem(self, request, context):
        """Mensagem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMensagens(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUsuario,
                    request_deserializer=service__pb2.UsuarioRequest.FromString,
                    response_serializer=service__pb2.Usuario.SerializeToString,
            ),
            'GetUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuario,
                    request_deserializer=service__pb2.Email.FromString,
                    response_serializer=service__pb2.Usuario.SerializeToString,
            ),
            'UpdateUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUsuario,
                    request_deserializer=service__pb2.UsuarioRequest.FromString,
                    response_serializer=service__pb2.Usuario.SerializeToString,
            ),
            'DeleteUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUsuario,
                    request_deserializer=service__pb2.Email.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsuarios,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=service__pb2.Usuarios.SerializeToString,
            ),
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=service__pb2.ChatRequest.FromString,
                    response_serializer=service__pb2.Chat.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=service__pb2.DataChat.FromString,
                    response_serializer=service__pb2.Chat.SerializeToString,
            ),
            'UpdateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChat,
                    request_deserializer=service__pb2.ChatRequest.FromString,
                    response_serializer=service__pb2.Chat.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=service__pb2.idChat.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetChats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChats,
                    request_deserializer=service__pb2.Email.FromString,
                    response_serializer=service__pb2.Chats.SerializeToString,
            ),
            'CreateMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMensagem,
                    request_deserializer=service__pb2.MensagemRequest.FromString,
                    response_serializer=service__pb2.Mensagem.SerializeToString,
            ),
            'GetMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMensagem,
                    request_deserializer=service__pb2.DataMensagem.FromString,
                    response_serializer=service__pb2.Mensagem.SerializeToString,
            ),
            'UpdateMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMensagem,
                    request_deserializer=service__pb2.MensagemRequest.FromString,
                    response_serializer=service__pb2.Mensagem.SerializeToString,
            ),
            'DeleteMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMensagem,
                    request_deserializer=service__pb2.idMensagem.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMensagens': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMensagens,
                    request_deserializer=service__pb2.idChat.FromString,
                    response_serializer=service__pb2.Mensagens.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateUsuario',
            service__pb2.UsuarioRequest.SerializeToString,
            service__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetUsuario',
            service__pb2.Email.SerializeToString,
            service__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateUsuario',
            service__pb2.UsuarioRequest.SerializeToString,
            service__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteUsuario',
            service__pb2.Email.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetUsuarios',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            service__pb2.Usuarios.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateChat',
            service__pb2.ChatRequest.SerializeToString,
            service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetChat',
            service__pb2.DataChat.SerializeToString,
            service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateChat',
            service__pb2.ChatRequest.SerializeToString,
            service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteChat',
            service__pb2.idChat.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetChats',
            service__pb2.Email.SerializeToString,
            service__pb2.Chats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateMensagem',
            service__pb2.MensagemRequest.SerializeToString,
            service__pb2.Mensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetMensagem',
            service__pb2.DataMensagem.SerializeToString,
            service__pb2.Mensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateMensagem',
            service__pb2.MensagemRequest.SerializeToString,
            service__pb2.Mensagem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteMensagem',
            service__pb2.idMensagem.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMensagens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetMensagens',
            service__pb2.idChat.SerializeToString,
            service__pb2.Mensagens.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
