// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protos/service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsuarioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Nome  string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Senha string `protobuf:"bytes,3,opt,name=senha,proto3" json:"senha,omitempty"`
}

func (x *UsuarioRequest) Reset() {
	*x = UsuarioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioRequest) ProtoMessage() {}

func (x *UsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioRequest.ProtoReflect.Descriptor instead.
func (*UsuarioRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{0}
}

func (x *UsuarioRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UsuarioRequest) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *UsuarioRequest) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdChat int64  `protobuf:"varint,1,opt,name=id_chat,json=idChat,proto3" json:"id_chat,omitempty"`
	Tema   string `protobuf:"bytes,2,opt,name=tema,proto3" json:"tema,omitempty"`
	Email  string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *ChatRequest) GetTema() string {
	if x != nil {
		return x.Tema
	}
	return ""
}

func (x *ChatRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MensagemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdMensagem int64  `protobuf:"varint,1,opt,name=idMensagem,proto3" json:"idMensagem,omitempty"`
	Pergunta   string `protobuf:"bytes,2,opt,name=pergunta,proto3" json:"pergunta,omitempty"`
	Resposta   string `protobuf:"bytes,3,opt,name=resposta,proto3" json:"resposta,omitempty"`
	IdChat     int64  `protobuf:"varint,4,opt,name=idChat,proto3" json:"idChat,omitempty"`
}

func (x *MensagemRequest) Reset() {
	*x = MensagemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MensagemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MensagemRequest) ProtoMessage() {}

func (x *MensagemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MensagemRequest.ProtoReflect.Descriptor instead.
func (*MensagemRequest) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{2}
}

func (x *MensagemRequest) GetIdMensagem() int64 {
	if x != nil {
		return x.IdMensagem
	}
	return 0
}

func (x *MensagemRequest) GetPergunta() string {
	if x != nil {
		return x.Pergunta
	}
	return ""
}

func (x *MensagemRequest) GetResposta() string {
	if x != nil {
		return x.Resposta
	}
	return ""
}

func (x *MensagemRequest) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type Email struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Email) Reset() {
	*x = Email{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{3}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type IdMensagem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdMensagem int64 `protobuf:"varint,1,opt,name=idMensagem,proto3" json:"idMensagem,omitempty"`
}

func (x *IdMensagem) Reset() {
	*x = IdMensagem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdMensagem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMensagem) ProtoMessage() {}

func (x *IdMensagem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMensagem.ProtoReflect.Descriptor instead.
func (*IdMensagem) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{4}
}

func (x *IdMensagem) GetIdMensagem() int64 {
	if x != nil {
		return x.IdMensagem
	}
	return 0
}

type IdChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdChat int64 `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
}

func (x *IdChat) Reset() {
	*x = IdChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdChat) ProtoMessage() {}

func (x *IdChat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdChat.ProtoReflect.Descriptor instead.
func (*IdChat) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{5}
}

func (x *IdChat) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type DataChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdChat int64  `protobuf:"varint,1,opt,name=idChat,proto3" json:"idChat,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *DataChat) Reset() {
	*x = DataChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChat) ProtoMessage() {}

func (x *DataChat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChat.ProtoReflect.Descriptor instead.
func (*DataChat) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{6}
}

func (x *DataChat) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *DataChat) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DataMensagem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdMensagem int64 `protobuf:"varint,1,opt,name=idMensagem,proto3" json:"idMensagem,omitempty"`
	IdChat     int64 `protobuf:"varint,2,opt,name=idChat,proto3" json:"idChat,omitempty"`
}

func (x *DataMensagem) Reset() {
	*x = DataMensagem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataMensagem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataMensagem) ProtoMessage() {}

func (x *DataMensagem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataMensagem.ProtoReflect.Descriptor instead.
func (*DataMensagem) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{7}
}

func (x *DataMensagem) GetIdMensagem() int64 {
	if x != nil {
		return x.IdMensagem
	}
	return 0
}

func (x *DataMensagem) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type Usuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome  string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Senha string `protobuf:"bytes,3,opt,name=senha,proto3" json:"senha,omitempty"`
}

func (x *Usuario) Reset() {
	*x = Usuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuario) ProtoMessage() {}

func (x *Usuario) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuario.ProtoReflect.Descriptor instead.
func (*Usuario) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{8}
}

func (x *Usuario) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Usuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Usuario) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

type Usuarios struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuarios []*Usuario `protobuf:"bytes,1,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *Usuarios) Reset() {
	*x = Usuarios{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usuarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuarios) ProtoMessage() {}

func (x *Usuarios) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuarios.ProtoReflect.Descriptor instead.
func (*Usuarios) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{9}
}

func (x *Usuarios) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdChat      int64                  `protobuf:"varint,1,opt,name=id_chat,json=idChat,proto3" json:"id_chat,omitempty"`
	Tema        string                 `protobuf:"bytes,2,opt,name=tema,proto3" json:"tema,omitempty"`
	DataCriacao *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=data_criacao,json=dataCriacao,proto3" json:"data_criacao,omitempty"`
	Email       string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{10}
}

func (x *Chat) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

func (x *Chat) GetTema() string {
	if x != nil {
		return x.Tema
	}
	return ""
}

func (x *Chat) GetDataCriacao() *timestamppb.Timestamp {
	if x != nil {
		return x.DataCriacao
	}
	return nil
}

func (x *Chat) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Chats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chats []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
}

func (x *Chats) Reset() {
	*x = Chats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chats) ProtoMessage() {}

func (x *Chats) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chats.ProtoReflect.Descriptor instead.
func (*Chats) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{11}
}

func (x *Chats) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type Mensagem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdMensagem int64                  `protobuf:"varint,1,opt,name=idMensagem,proto3" json:"idMensagem,omitempty"`
	Pergunta   string                 `protobuf:"bytes,2,opt,name=pergunta,proto3" json:"pergunta,omitempty"`
	Resposta   string                 `protobuf:"bytes,3,opt,name=resposta,proto3" json:"resposta,omitempty"`
	DataHora   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dataHora,proto3" json:"dataHora,omitempty"`
	IdChat     int64                  `protobuf:"varint,5,opt,name=idChat,proto3" json:"idChat,omitempty"`
}

func (x *Mensagem) Reset() {
	*x = Mensagem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mensagem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensagem) ProtoMessage() {}

func (x *Mensagem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensagem.ProtoReflect.Descriptor instead.
func (*Mensagem) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{12}
}

func (x *Mensagem) GetIdMensagem() int64 {
	if x != nil {
		return x.IdMensagem
	}
	return 0
}

func (x *Mensagem) GetPergunta() string {
	if x != nil {
		return x.Pergunta
	}
	return ""
}

func (x *Mensagem) GetResposta() string {
	if x != nil {
		return x.Resposta
	}
	return ""
}

func (x *Mensagem) GetDataHora() *timestamppb.Timestamp {
	if x != nil {
		return x.DataHora
	}
	return nil
}

func (x *Mensagem) GetIdChat() int64 {
	if x != nil {
		return x.IdChat
	}
	return 0
}

type Mensagens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mensagens []*Mensagem `protobuf:"bytes,1,rep,name=mensagens,proto3" json:"mensagens,omitempty"`
}

func (x *Mensagens) Reset() {
	*x = Mensagens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mensagens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensagens) ProtoMessage() {}

func (x *Mensagens) ProtoReflect() protoreflect.Message {
	mi := &file_protos_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensagens.ProtoReflect.Descriptor instead.
func (*Mensagens) Descriptor() ([]byte, []int) {
	return file_protos_service_proto_rawDescGZIP(), []int{13}
}

func (x *Mensagens) GetMensagens() []*Mensagem {
	if x != nil {
		return x.Mensagens
	}
	return nil
}

var File_protos_service_proto protoreflect.FileDescriptor

var file_protos_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x22, 0x50, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x4d, 0x65, 0x6e,
	0x73, 0x61, 0x67, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x69, 0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x65, 0x72, 0x67, 0x75, 0x6e, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x65, 0x72, 0x67, 0x75, 0x6e, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x73, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x73, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x22, 0x1d, 0x0a, 0x05,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2c, 0x0a, 0x0a, 0x69,
	0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x4d,
	0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69,
	0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x22, 0x20, 0x0a, 0x06, 0x69, 0x64, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x22, 0x38, 0x0a, 0x08, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x68, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x46, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x6e,
	0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61,
	0x67, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x64, 0x4d, 0x65, 0x6e,
	0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x22, 0x49, 0x0a,
	0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x65, 0x6e, 0x68, 0x61, 0x22, 0x30, 0x0a, 0x08, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x73, 0x12, 0x24, 0x0a, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f,
	0x52, 0x08, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x04, 0x43,
	0x68, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x61,
	0x12, 0x3d, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x72, 0x69, 0x61, 0x63, 0x61, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x43, 0x72, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x24, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x74, 0x73, 0x12, 0x1b,
	0x0a, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x08,
	0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x4d, 0x65,
	0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69, 0x64,
	0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x67,
	0x75, 0x6e, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x72, 0x67,
	0x75, 0x6e, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x74, 0x61,
	0x12, 0x36, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x48, 0x6f, 0x72, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x61, 0x48, 0x6f, 0x72, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x43, 0x68,
	0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74,
	0x22, 0x34, 0x0a, 0x09, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x73, 0x12, 0x27, 0x0a,
	0x09, 0x6d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x52, 0x09, 0x6d, 0x65, 0x6e,
	0x73, 0x61, 0x67, 0x65, 0x6e, 0x73, 0x32, 0x97, 0x05, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x22, 0x00, 0x12, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x08, 0x2e, 0x55, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x0f, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x09,
	0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0c, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x05, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x22, 0x00,
	0x12, 0x1d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12, 0x09, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x43, 0x68, 0x61, 0x74, 0x1a, 0x05, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x22, 0x00, 0x12,
	0x23, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0c, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x05, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x07, 0x2e, 0x69, 0x64, 0x43, 0x68, 0x61, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74,
	0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0x06, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e,
	0x73, 0x61, 0x67, 0x65, 0x6d, 0x12, 0x10, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67,
	0x65, 0x6d, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x73, 0x61,
	0x67, 0x65, 0x6d, 0x12, 0x0d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67,
	0x65, 0x6d, 0x1a, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x22, 0x00, 0x12,
	0x2f, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65,
	0x6d, 0x12, 0x10, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x22, 0x00,
	0x12, 0x37, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67,
	0x65, 0x6d, 0x12, 0x0b, 0x2e, 0x69, 0x64, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6d, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x73, 0x12, 0x07, 0x2e, 0x69, 0x64, 0x43, 0x68,
	0x61, 0x74, 0x1a, 0x0a, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x67, 0x65, 0x6e, 0x73, 0x22, 0x00,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_service_proto_rawDescOnce sync.Once
	file_protos_service_proto_rawDescData = file_protos_service_proto_rawDesc
)

func file_protos_service_proto_rawDescGZIP() []byte {
	file_protos_service_proto_rawDescOnce.Do(func() {
		file_protos_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_service_proto_rawDescData)
	})
	return file_protos_service_proto_rawDescData
}

var file_protos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protos_service_proto_goTypes = []interface{}{
	(*UsuarioRequest)(nil),        // 0: UsuarioRequest
	(*ChatRequest)(nil),           // 1: ChatRequest
	(*MensagemRequest)(nil),       // 2: MensagemRequest
	(*Email)(nil),                 // 3: Email
	(*IdMensagem)(nil),            // 4: idMensagem
	(*IdChat)(nil),                // 5: idChat
	(*DataChat)(nil),              // 6: DataChat
	(*DataMensagem)(nil),          // 7: DataMensagem
	(*Usuario)(nil),               // 8: Usuario
	(*Usuarios)(nil),              // 9: Usuarios
	(*Chat)(nil),                  // 10: Chat
	(*Chats)(nil),                 // 11: Chats
	(*Mensagem)(nil),              // 12: Mensagem
	(*Mensagens)(nil),             // 13: Mensagens
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_protos_service_proto_depIdxs = []int32{
	8,  // 0: Usuarios.usuarios:type_name -> Usuario
	14, // 1: Chat.data_criacao:type_name -> google.protobuf.Timestamp
	10, // 2: Chats.chats:type_name -> Chat
	14, // 3: Mensagem.dataHora:type_name -> google.protobuf.Timestamp
	12, // 4: Mensagens.mensagens:type_name -> Mensagem
	0,  // 5: DataService.CreateUsuario:input_type -> UsuarioRequest
	3,  // 6: DataService.GetUsuario:input_type -> Email
	0,  // 7: DataService.UpdateUsuario:input_type -> UsuarioRequest
	3,  // 8: DataService.DeleteUsuario:input_type -> Email
	15, // 9: DataService.GetUsuarios:input_type -> google.protobuf.Empty
	1,  // 10: DataService.CreateChat:input_type -> ChatRequest
	6,  // 11: DataService.GetChat:input_type -> DataChat
	1,  // 12: DataService.UpdateChat:input_type -> ChatRequest
	5,  // 13: DataService.DeleteChat:input_type -> idChat
	3,  // 14: DataService.GetChats:input_type -> Email
	2,  // 15: DataService.CreateMensagem:input_type -> MensagemRequest
	7,  // 16: DataService.GetMensagem:input_type -> DataMensagem
	2,  // 17: DataService.UpdateMensagem:input_type -> MensagemRequest
	4,  // 18: DataService.DeleteMensagem:input_type -> idMensagem
	5,  // 19: DataService.GetMensagens:input_type -> idChat
	8,  // 20: DataService.CreateUsuario:output_type -> Usuario
	8,  // 21: DataService.GetUsuario:output_type -> Usuario
	8,  // 22: DataService.UpdateUsuario:output_type -> Usuario
	15, // 23: DataService.DeleteUsuario:output_type -> google.protobuf.Empty
	9,  // 24: DataService.GetUsuarios:output_type -> Usuarios
	10, // 25: DataService.CreateChat:output_type -> Chat
	10, // 26: DataService.GetChat:output_type -> Chat
	10, // 27: DataService.UpdateChat:output_type -> Chat
	15, // 28: DataService.DeleteChat:output_type -> google.protobuf.Empty
	11, // 29: DataService.GetChats:output_type -> Chats
	12, // 30: DataService.CreateMensagem:output_type -> Mensagem
	12, // 31: DataService.GetMensagem:output_type -> Mensagem
	12, // 32: DataService.UpdateMensagem:output_type -> Mensagem
	15, // 33: DataService.DeleteMensagem:output_type -> google.protobuf.Empty
	13, // 34: DataService.GetMensagens:output_type -> Mensagens
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protos_service_proto_init() }
func file_protos_service_proto_init() {
	if File_protos_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsuarioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MensagemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Email); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdMensagem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataMensagem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Usuarios); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mensagem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mensagens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_service_proto_goTypes,
		DependencyIndexes: file_protos_service_proto_depIdxs,
		MessageInfos:      file_protos_service_proto_msgTypes,
	}.Build()
	File_protos_service_proto = out.File
	file_protos_service_proto_rawDesc = nil
	file_protos_service_proto_goTypes = nil
	file_protos_service_proto_depIdxs = nil
}
