# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x0f\n\rHealthRequest\".\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05model\x18\x02 \x01(\t\"\x8f\x01\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\nmax_tokens\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0btemperature\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x12\n\x05model\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\r\n\x0b_max_tokensB\x0e\n\x0c_temperatureB\x08\n\x06_model\"L\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x12\n\x05\x65rror\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"\"\n\x0cModelRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"1\n\rModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x9f\x01\n\nLLMService\x12\x30\n\x0bHealthCheck\x12\x0e.HealthRequest\x1a\x0f.HealthResponse\"\x00\x12\x31\n\x0cGenerateText\x12\x0e.PromptRequest\x1a\r.TextResponse\"\x00\x30\x01\x12,\n\tLoadModel\x12\r.ModelRequest\x1a\x0e.ModelResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=17
  _globals['_HEALTHREQUEST']._serialized_end=32
  _globals['_HEALTHRESPONSE']._serialized_start=34
  _globals['_HEALTHRESPONSE']._serialized_end=80
  _globals['_PROMPTREQUEST']._serialized_start=83
  _globals['_PROMPTREQUEST']._serialized_end=226
  _globals['_TEXTRESPONSE']._serialized_start=228
  _globals['_TEXTRESPONSE']._serialized_end=304
  _globals['_MODELREQUEST']._serialized_start=306
  _globals['_MODELREQUEST']._serialized_end=340
  _globals['_MODELRESPONSE']._serialized_start=342
  _globals['_MODELRESPONSE']._serialized_end=391
  _globals['_LLMSERVICE']._serialized_start=394
  _globals['_LLMSERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
