CREATE TABLE "User" (
    idUser SERIAL PRIMARY KEY,
    "name" VARCHAR(50) NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Chat (
    idChat SERIAL PRIMARY KEY,
    "subject" VARCHAR(60),
    startDate DATE NOT NULL DEFAULT CURRENT_DATE,
    fkIdUser INTEGER,
    CONSTRAINT fk_Chat FOREIGN KEY (fkIdUser) REFERENCES "User" (idUser) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE Message (
    idMessage SERIAL PRIMARY KEY,
    "dateTime" TIMESTAMP NOT NULL DEFAULT NOW(),
    content TEXT NOT NULL,
    fkIdChat INTEGER,
    CONSTRAINT fk_Message FOREIGN KEY (fkIdChat) REFERENCES Chat (idChat) ON DELETE RESTRICT ON UPDATE CASCADE
);