CREATE TABLE "USER" (
    "name" VARCHAR(50) NOT NULL,
    email VARCHAR(30) NOT NULL PRIMARY KEY,
    "password" VARCHAR(255) NOT NULL
);

CREATE TABLE CHAT (
    idChat SERIAL PRIMARY KEY,
    "subject" VARCHAR(60),
    startDate DATE NOT NULL DEFAULT CURRENT_DATE,
    email VARCHAR(30) NOT NULL,
    CONSTRAINT CHAT_USER_FK FOREIGN KEY (email) REFERENCES "USER" (email) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE MESSAGE (
    idMessage SERIAL PRIMARY KEY,
    "dateTime" TIMESTAMP NOT NULL DEFAULT NOW(),
    content TEXT NOT NULL,
    idChat INTEGER,
    CONSTRAINT MESSAGE_CHAT_FK FOREIGN KEY (idChat) REFERENCES CHAT (idChat) ON DELETE RESTRICT ON UPDATE CASCADE
);