services:
  db:
    image: postgres:latest
    container_name: postgres_pspd
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pspdlabs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DML.sql:/docker-entrypoint-initdb.d/DML.sql:ro

volumes:
  pgdata:
  DML.sql: