/* logico: */

CREATE TABLE USUARIO (
    idUsuario SERIAL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(30) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE CHAT (
    idChat SERIAL PRIMARY KEY,
    tema VARCHAR(60),
    dataInicio DATE NOT NULL DEFAULT CURRENT_DATE,
    fkIdUsuario SERIAL
);

CREATE TABLE MENSAGEM (
    idMensagem SERIAL PRIMARY KEY,
    dataHora TIMESTAMP NOT NULL DEFAULT NOW(),
    conteudo TEXT NOT NULL,
    fkIdChat SERIAL
);
 
ALTER TABLE CHAT ADD CONSTRAINT FK_CHAT_2
    FOREIGN KEY (fkIdUsuario)
    REFERENCES USUARIO (idUsuario)
    ON DELETE RESTRICT ON UPDATE CASCADE;
 
ALTER TABLE MENSAGEM ADD CONSTRAINT FK_MENSAGEM_2
    FOREIGN KEY (fkIdChat)
    REFERENCES CHAT (idChat)
    ON DELETE SET NULL;