# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_services import service_pb2 as grpc__services_dot_service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_services/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/DataService/CreateUser',
                request_serializer=grpc__services_dot_service__pb2.UserCreateUpdateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.User.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/DataService/GetUser',
                request_serializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/DataService/UpdateUser',
                request_serializer=grpc__services_dot_service__pb2.UserCreateUpdateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/DataService/DeleteUser',
                request_serializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/DataService/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Users.FromString,
                _registered_method=True)
        self.CreateChat = channel.unary_unary(
                '/DataService/CreateChat',
                request_serializer=grpc__services_dot_service__pb2.ChatCreateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Chat.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/DataService/GetChat',
                request_serializer=grpc__services_dot_service__pb2.ChatReadRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Chat.FromString,
                _registered_method=True)
        self.UpdateChat = channel.unary_unary(
                '/DataService/UpdateChat',
                request_serializer=grpc__services_dot_service__pb2.ChatUpdateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Chat.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/DataService/DeleteChat',
                request_serializer=grpc__services_dot_service__pb2.ChatDeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/DataService/ListChats',
                request_serializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Chats.FromString,
                _registered_method=True)
        self.CreateMessage = channel.unary_unary(
                '/DataService/CreateMessage',
                request_serializer=grpc__services_dot_service__pb2.MessageCreateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Message.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/DataService/GetMessage',
                request_serializer=grpc__services_dot_service__pb2.MessageReadRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Message.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/DataService/UpdateMessage',
                request_serializer=grpc__services_dot_service__pb2.MessageUpdateRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Message.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/DataService/DeleteMessage',
                request_serializer=grpc__services_dot_service__pb2.MessageDeleteRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/DataService/ListMessages',
                request_serializer=grpc__services_dot_service__pb2.ChatDeleteRequest.SerializeToString,
                response_deserializer=grpc__services_dot_service__pb2.Messages.FromString,
                _registered_method=True)


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """User
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChat(self, request, context):
        """Chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMessage(self, request, context):
        """Message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=grpc__services_dot_service__pb2.UserCreateUpdateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.User.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=grpc__services_dot_service__pb2.UserCreateUpdateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Users.SerializeToString,
            ),
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=grpc__services_dot_service__pb2.ChatCreateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Chat.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=grpc__services_dot_service__pb2.ChatReadRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Chat.SerializeToString,
            ),
            'UpdateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChat,
                    request_deserializer=grpc__services_dot_service__pb2.ChatUpdateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Chat.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=grpc__services_dot_service__pb2.ChatDeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=grpc__services_dot_service__pb2.UserReadDeleteRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Chats.SerializeToString,
            ),
            'CreateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMessage,
                    request_deserializer=grpc__services_dot_service__pb2.MessageCreateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Message.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=grpc__services_dot_service__pb2.MessageReadRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Message.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=grpc__services_dot_service__pb2.MessageUpdateRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Message.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=grpc__services_dot_service__pb2.MessageDeleteRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=grpc__services_dot_service__pb2.ChatDeleteRequest.FromString,
                    response_serializer=grpc__services_dot_service__pb2.Messages.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateUser',
            grpc__services_dot_service__pb2.UserCreateUpdateRequest.SerializeToString,
            grpc__services_dot_service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetUser',
            grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
            grpc__services_dot_service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateUser',
            grpc__services_dot_service__pb2.UserCreateUpdateRequest.SerializeToString,
            grpc__services_dot_service__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteUser',
            grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__services_dot_service__pb2.Users.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateChat',
            grpc__services_dot_service__pb2.ChatCreateRequest.SerializeToString,
            grpc__services_dot_service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetChat',
            grpc__services_dot_service__pb2.ChatReadRequest.SerializeToString,
            grpc__services_dot_service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateChat',
            grpc__services_dot_service__pb2.ChatUpdateRequest.SerializeToString,
            grpc__services_dot_service__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteChat',
            grpc__services_dot_service__pb2.ChatDeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/ListChats',
            grpc__services_dot_service__pb2.UserReadDeleteRequest.SerializeToString,
            grpc__services_dot_service__pb2.Chats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/CreateMessage',
            grpc__services_dot_service__pb2.MessageCreateRequest.SerializeToString,
            grpc__services_dot_service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/GetMessage',
            grpc__services_dot_service__pb2.MessageReadRequest.SerializeToString,
            grpc__services_dot_service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/UpdateMessage',
            grpc__services_dot_service__pb2.MessageUpdateRequest.SerializeToString,
            grpc__services_dot_service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/DeleteMessage',
            grpc__services_dot_service__pb2.MessageDeleteRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DataService/ListMessages',
            grpc__services_dot_service__pb2.ChatDeleteRequest.SerializeToString,
            grpc__services_dot_service__pb2.Messages.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
